# shiny-server.conf — basic configuration for Shiny Server
run_as shiny;

server {
  listen 3838;
  location /TrajectoryDashboard {
    app_dir /srv/TrajectoryDashboard/inst/app;
    log_dir /var/log/shiny-server;
    directory_index off;
  }
}
